name: Bump new release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog
            semantic-release-gitmoji
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}